// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	asynq "github.com/hibiken/asynq"

	mock "github.com/stretchr/testify/mock"
)

// TaskProcessor is an autogenerated mock type for the TaskProcessor type
type TaskProcessor struct {
	mock.Mock
}

// ProcessTaskOrderConfirmation provides a mock function with given fields: ctx, t
func (_m *TaskProcessor) ProcessTaskOrderConfirmation(ctx context.Context, t *asynq.Task) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTaskOrderConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *asynq.Task) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskProcessor creates a new instance of TaskProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskProcessor {
	mock := &TaskProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
