// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	asynq "github.com/hibiken/asynq"

	mock "github.com/stretchr/testify/mock"

	task "github.com/yourusername/go-ecommerce-api/internal/task"
)

// TaskDistributor is an autogenerated mock type for the TaskDistributor type
type TaskDistributor struct {
	mock.Mock
}

// DistributeTaskOrderConfirmation provides a mock function with given fields: ctx, payload, opts
func (_m *TaskDistributor) DistributeTaskOrderConfirmation(ctx context.Context, payload task.OrderConfirmationPayload, opts ...asynq.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, payload)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DistributeTaskOrderConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, task.OrderConfirmationPayload, ...asynq.Option) error); ok {
		r0 = rf(ctx, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskDistributor creates a new instance of TaskDistributor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskDistributor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskDistributor {
	mock := &TaskDistributor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
